/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Returns `{"status": "ok"}` when the server process is running. Does not verify database connectivity — use this as a liveness probe only.
     */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Authenticate with email and password
     * @description Validates credentials and returns a JWT access token plus an opaque refresh token. The refresh token is stored hashed server-side and must be rotated on each use.
     */
    post: operations["login_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rotate refresh token and issue new access token
     * @description Consumes the provided refresh token (validates it is not revoked or expired), revokes it, and issues a new token pair. Rolling refresh — the old token becomes invalid.
     */
    post: operations["refresh_auth_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Revoke refresh token
     * @description Marks the supplied refresh token as revoked. Idempotent — calling with an already revoked or unknown token still returns 204.
     */
    post: operations["logout_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/password-reset/request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request a password reset email
     * @description Sends a password reset link to the supplied email if an account exists. Always returns 202 to prevent user enumeration.
     */
    post: operations["password_reset_request_auth_password_reset_request_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/password-reset/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Confirm password reset with token
     * @description Validates the reset token (checks expiry and not-used), sets the new password, and revokes all active refresh tokens for the user.
     */
    post: operations["password_reset_confirm_auth_password_reset_confirm_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Return the authenticated user's profile
     * @description Decodes the Bearer access token and returns the caller's profile.
     */
    get: operations["me_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/goddess/invitations/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all invitations created by the Goddess
     * @description Returns all invitations created by this Goddess, ordered newest first. Includes pending, expired, and used invitations.
     */
    get: operations["list_invitations_goddess_invitations__get"];
    put?: never;
    /**
     * Create an invitation link
     * @description Creates a new invitation token that a sub can use to sign up. Sets an entry tribute amount the sub must declare after signup. The invitation expires after `expires_in_days` days (default 7) and is single-use.
     */
    post: operations["create_invitation_goddess_invitations__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/goddess/payment-methods/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List payment methods
     * @description Returns all payment methods owned by the authenticated Goddess, ordered by sort_order ascending. Pass `?enabled=true` to return only enabled methods.
     */
    get: operations["list_payment_methods_goddess_payment_methods__get"];
    put?: never;
    /**
     * Create a payment method
     * @description Creates a new payment method for the authenticated Goddess. The new method receives sort_order = max(existing) + 1 (appended to the bottom).
     */
    post: operations["create_payment_method_goddess_payment_methods__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/goddess/payment-methods/{method_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Soft-delete a payment method
     * @description Disables a payment method by setting `enabled=false`. The record is retained for historical references in payment declarations.
     */
    delete: operations["delete_payment_method_goddess_payment_methods__method_id__delete"];
    options?: never;
    head?: never;
    /**
     * Update a payment method
     * @description Partially updates a payment method owned by the authenticated Goddess. Only fields present in the request body are changed (patch semantics).
     */
    patch: operations["update_payment_method_goddess_payment_methods__method_id__patch"];
    trace?: never;
  };
  "/goddess/payment-methods/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reorder payment methods
     * @description Accepts a list of all payment method IDs in the desired display order. The position in the list becomes the new sort_order (0 = top). Raises 400 if any ID does not belong to this Goddess.
     */
    post: operations["reorder_payment_methods_goddess_payment_methods_reorder_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/invite/{token}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Fetch public invitation details
     * @description Returns the public information for a valid, unused, non-expired invitation. Used by the invitation landing page before the sub signs up.
     */
    get: operations["get_invitation_invite__token__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/invite/{token}/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sign up via invitation link
     * @description Creates a new sub account linked to the Goddess who owns the invitation. The sub is created with `status=pending_entry_tribute`. The invitation token is consumed atomically with user creation. Returns a token pair so the sub is immediately logged in.
     */
    post: operations["signup_via_invite_invite__token__signup_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sub/payments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List own payment history
     * @description Returns the authenticated sub's payment declarations ordered by declared_at descending.
     */
    get: operations["list_my_payments_sub_payments_get"];
    put?: never;
    /**
     * Declare a payment
     * @description Sub declares a payment they have made. Creates a pending declaration. Category `entry` only allowed while sub status is `pending_entry_tribute`. Category `tribute` allowed for active subs. Categories `rolling`, `weekly_debt`, `debt_payment`, `buyout` are reserved for future phases.
     */
    post: operations["declare_payment_sub_payments_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sub/payments/{declaration_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Cancel a pending declaration
     * @description Marks a pending declaration as cancelled. Raises 409 if not pending. Cancelled declarations remain in history.
     */
    delete: operations["cancel_declaration_sub_payments__declaration_id__delete"];
    options?: never;
    head?: never;
    /**
     * Edit a pending declaration
     * @description Partially updates a pending declaration owned by this sub. Only fields supplied are changed. Raises 409 if declaration is not pending.
     */
    patch: operations["edit_declaration_sub_payments__declaration_id__patch"];
    trace?: never;
  };
  "/sub/payment-methods": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List enabled payment methods for sub's goddess
     * @description Returns the enabled payment methods belonging to the authenticated sub's goddess. Used by subs when filing a payment declaration.
     */
    get: operations["list_sub_payment_methods_sub_payment_methods_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/goddess/payments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List pending payment declarations
     * @description Returns declarations for this goddess filtered by status. Currently only `status=pending` is supported. Other values are ignored and return pending.
     */
    get: operations["list_pending_payments_goddess_payments_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/goddess/payments/{declaration_id}/validate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Validate a pending declaration
     * @description Validates a pending declaration, optionally re-categorising it first. Emits a payment allocation. On `entry` category, promotes the sub to `active`. Raises 409 if declaration is not pending.
     */
    post: operations["validate_declaration_goddess_payments__declaration_id__validate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/goddess/payments/{declaration_id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reject a pending declaration
     * @description Marks a pending declaration as rejected with an optional reason. Raises 409 if declaration is not pending.
     */
    post: operations["reject_declaration_goddess_payments__declaration_id__reject_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/goddess/payments/record": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Record a payment on behalf of a sub
     * @description Goddess creates an already-validated declaration on behalf of a sub. Emits allocation immediately. On `entry` category, promotes sub to `active`.
     */
    post: operations["record_payment_goddess_payments_record_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/goddess/subs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List subs for this goddess
     * @description Returns a minimal list of users linked to the authenticated goddess.
     */
    get: operations["list_goddess_subs_goddess_subs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AllocationOut */
    AllocationOut: {
      /**
       * @description What ledger bucket received this allocation
       * @example entry
       */
      target_type: components["schemas"]["AllocationTargetType"];
      /**
       * Target Id
       * @description Polymorphic target ID (None for entry/tribute)
       * @example null
       */
      target_id?: string | null;
      /**
       * Amount
       * @description Allocated amount in GBP
       * @example 30.00
       */
      amount: string;
      /**
       * Allocated At
       * Format: date-time
       * @description UTC datetime when the allocation was emitted
       */
      allocated_at: string;
    };
    /**
     * AllocationTargetType
     * @enum {string}
     */
    AllocationTargetType:
      | "entry"
      | "rolling_cycle"
      | "contract_debt"
      | "contract_buyout"
      | "tribute";
    /** DeclarePaymentIn */
    DeclarePaymentIn: {
      /**
       * Amount
       * @description Payment amount in GBP
       * @example 30.00
       */
      amount: number | string;
      /**
       * Method Id
       * Format: uuid
       * @description UUID of the payment method used
       * @example 00000000-0000-0000-0000-000000000001
       */
      method_id: string;
      /**
       * @description Payment category — determines ledger routing
       * @example entry
       */
      category: components["schemas"]["PaymentCategory"];
      /**
       * External Timestamp
       * @description UTC datetime when the payment was actually made (sub-reported)
       * @example 2026-04-13T12:00:00
       */
      external_timestamp?: string | null;
      /**
       * Note
       * @description Optional note from the sub
       * @example Sent via Throne
       */
      note?: string | null;
      /**
       * Target Id
       * @description Polymorphic target — contract or rolling cycle ID (required for some categories)
       * @example null
       */
      target_id?: string | null;
    };
    /** EditDeclarationIn */
    EditDeclarationIn: {
      /**
       * Amount
       * @description Updated payment amount in GBP
       * @example 30.00
       */
      amount?: number | string | null;
      /**
       * Method Id
       * @description Updated payment method UUID
       * @example 00000000-0000-0000-0000-000000000001
       */
      method_id?: string | null;
      /**
       * @description Updated payment category
       * @example tribute
       */
      category?: components["schemas"]["PaymentCategory"] | null;
      /**
       * External Timestamp
       * @description Updated external payment timestamp
       * @example 2026-04-13T12:00:00
       */
      external_timestamp?: string | null;
      /**
       * Note
       * @description Updated note
       * @example Corrected note
       */
      note?: string | null;
      /**
       * Target Id
       * @description Updated polymorphic target ID
       * @example null
       */
      target_id?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InvitationCreate */
    InvitationCreate: {
      /**
       * Entry Tribute Amount
       * @description Entry tribute amount in GBP that the sub must declare on signup
       * @example 50.00
       */
      entry_tribute_amount: number | string;
      /**
       * Note
       * @description Optional private note visible to the sub on the invitation landing page
       * @example Welcome, slave.
       */
      note?: string | null;
      /**
       * Expires In Days
       * @description How many days from now until the invitation link expires
       * @default 7
       * @example 7
       */
      expires_in_days: number;
    };
    /** InvitationOut */
    InvitationOut: {
      /**
       * Id
       * Format: uuid
       * @description Invitation UUID
       * @example 00000000-0000-0000-0000-000000000001
       */
      id: string;
      /**
       * Token
       * @description URL-safe token embedded in the invite link
       * @example abc123xyz
       */
      token: string;
      /**
       * Url
       * @description Full invite URL to share with the sub
       * @example http://localhost:5173/invite/abc123xyz
       */
      url: string;
      /**
       * Entry Tribute Amount
       * @description Entry tribute amount in GBP
       * @example 50.00
       */
      entry_tribute_amount: string;
      /**
       * Note
       * @description Optional note
       * @example Welcome.
       */
      note?: string | null;
      /**
       * Expires At
       * Format: date-time
       * @description UTC expiry datetime of the invitation
       */
      expires_at: string;
      /**
       * Used At
       * @description UTC datetime when the invitation was consumed
       */
      used_at?: string | null;
      /**
       * Created At
       * Format: date-time
       * @description UTC datetime when the invitation was created
       */
      created_at: string;
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * @description User email address
       * @example sub@example.com
       */
      email: string;
      /**
       * Password
       * @description User password
       * @example s3cr3t!
       */
      password: string;
    };
    /** PasswordResetConfirm */
    PasswordResetConfirm: {
      /**
       * Token
       * @description Reset token from the email link
       * @example abc123
       */
      token: string;
      /**
       * New Password
       * @description New password to set (min 8 chars)
       * @example n3wP@ssw0rd
       */
      new_password: string;
    };
    /** PasswordResetRequest */
    PasswordResetRequest: {
      /**
       * Email
       * Format: email
       * @description Email address of the account to reset
       * @example sub@example.com
       */
      email: string;
    };
    /**
     * PaymentCategory
     * @enum {string}
     */
    PaymentCategory: "entry" | "rolling" | "weekly_debt" | "debt_payment" | "buyout" | "tribute";
    /** PaymentMethodCreate */
    PaymentMethodCreate: {
      /**
       * Name
       * @description Display label for this payment method
       * @example Throne — jane-mm
       */
      name: string;
      /**
       * @description Category of payment method
       * @example throne
       */
      type: components["schemas"]["PaymentMethodType"];
      /**
       * Handle Or Link
       * @description The @handle, URL, or account reference for this method
       * @example @jane-mm
       */
      handle_or_link: string;
      /**
       * Note
       * @description Optional free-text note visible to Goddess only
       * @example Primary tribute method
       */
      note?: string | null;
      /**
       * Enabled
       * @description Whether this method is active and shown to subs
       * @default true
       * @example true
       */
      enabled: boolean;
    };
    /** PaymentMethodOut */
    PaymentMethodOut: {
      /**
       * Id
       * Format: uuid
       * @description Payment method UUID
       * @example 00000000-0000-0000-0000-000000000001
       */
      id: string;
      /**
       * Name
       * @description Display label for this payment method
       * @example Throne — jane-mm
       */
      name: string;
      /**
       * @description Category of payment method
       * @example throne
       */
      type: components["schemas"]["PaymentMethodType"];
      /**
       * Handle Or Link
       * @description The @handle, URL, or account reference
       * @example @jane-mm
       */
      handle_or_link: string;
      /**
       * Note
       * @description Optional free-text note
       * @example Primary tribute method
       */
      note?: string | null;
      /**
       * Enabled
       * @description Whether this method is active
       * @example true
       */
      enabled: boolean;
      /**
       * Sort Order
       * @description Display order (ascending = top)
       * @example 0
       */
      sort_order: number;
      /**
       * Created At
       * Format: date-time
       * @description UTC datetime when the method was created
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       * @description UTC datetime when the method was last updated
       */
      updated_at: string;
    };
    /**
     * PaymentMethodType
     * @enum {string}
     */
    PaymentMethodType: "throne" | "paypal" | "bank" | "other";
    /** PaymentMethodUpdate */
    PaymentMethodUpdate: {
      /**
       * Name
       * @description Updated display label
       * @example Throne — jane-mm
       */
      name?: string | null;
      /**
       * @description Updated payment method category
       * @example paypal
       */
      type?: components["schemas"]["PaymentMethodType"] | null;
      /**
       * Handle Or Link
       * @description Updated @handle, URL, or account reference
       * @example paypal.me/jane-mm
       */
      handle_or_link?: string | null;
      /**
       * Note
       * @description Updated free-text note
       * @example Secondary method
       */
      note?: string | null;
      /**
       * Enabled
       * @description Enable or disable this method
       * @example false
       */
      enabled?: boolean | null;
    };
    /** PaymentOut */
    PaymentOut: {
      /**
       * Id
       * Format: uuid
       * @description Declaration UUID
       * @example 00000000-0000-0000-0000-000000000001
       */
      id: string;
      /**
       * Sub Id
       * Format: uuid
       * @description Sub user UUID
       */
      sub_id: string;
      /**
       * Sub Display Name
       * @description Sub display name (first + last)
       */
      sub_display_name?: string | null;
      /**
       * Goddess Id
       * Format: uuid
       * @description Goddess UUID
       */
      goddess_id: string;
      /**
       * Method Id
       * Format: uuid
       * @description Payment method UUID
       */
      method_id: string;
      /**
       * Method Name
       * @description Payment method display name
       */
      method_name?: string | null;
      /**
       * Amount
       * @description Payment amount in GBP
       * @example 30.00
       */
      amount: string;
      /**
       * External Timestamp
       * @description Sub-reported payment datetime
       */
      external_timestamp?: string | null;
      /**
       * Note
       * @description Note from the declarer
       */
      note?: string | null;
      /**
       * @description Payment category
       * @example entry
       */
      category: components["schemas"]["PaymentCategory"];
      /**
       * @description Declaration status
       * @example pending
       */
      status: components["schemas"]["PaymentStatus"];
      /**
       * Target Id
       * @description Polymorphic target ID
       */
      target_id?: string | null;
      /**
       * Created By
       * Format: uuid
       * @description UUID of user who created this declaration
       */
      created_by: string;
      /**
       * Declared At
       * Format: date-time
       * @description UTC datetime of declaration
       */
      declared_at: string;
      /**
       * Validated At
       * @description UTC datetime of validation/rejection
       */
      validated_at?: string | null;
      /**
       * Validated By
       * @description UUID of goddess who validated/rejected
       */
      validated_by?: string | null;
      /**
       * Rejection Reason
       * @description Reason for rejection if rejected
       */
      rejection_reason?: string | null;
      /** @description Allocation record if validated */
      allocation?: components["schemas"]["AllocationOut"] | null;
    };
    /**
     * PaymentStatus
     * @enum {string}
     */
    PaymentStatus: "pending" | "validated" | "rejected" | "cancelled";
    /** PublicInvitationOut */
    PublicInvitationOut: {
      /**
       * Token
       * @description Invitation token
       * @example abc123xyz
       */
      token: string;
      /**
       * Goddess Display Name
       * @description Display name of the Goddess who created the invitation
       * @example Goddess Mean Mal
       */
      goddess_display_name: string;
      /**
       * Note
       * @description Optional note from the Goddess
       * @example Welcome.
       */
      note?: string | null;
      /**
       * Entry Tribute Amount
       * @description Amount the sub must tribute on signup (GBP)
       * @example 50.00
       */
      entry_tribute_amount: string;
      /**
       * Expires At
       * Format: date-time
       * @description UTC expiry datetime of the invitation
       */
      expires_at: string;
    };
    /** RecordPaymentIn */
    RecordPaymentIn: {
      /**
       * Amount
       * @description Payment amount in GBP
       * @example 30.00
       */
      amount: number | string;
      /**
       * Method Id
       * Format: uuid
       * @description UUID of the payment method used
       * @example 00000000-0000-0000-0000-000000000001
       */
      method_id: string;
      /**
       * @description Payment category — determines ledger routing
       * @example entry
       */
      category: components["schemas"]["PaymentCategory"];
      /**
       * External Timestamp
       * @description UTC datetime when the payment was actually made (sub-reported)
       * @example 2026-04-13T12:00:00
       */
      external_timestamp?: string | null;
      /**
       * Note
       * @description Optional note from the sub
       * @example Sent via Throne
       */
      note?: string | null;
      /**
       * Target Id
       * @description Polymorphic target — contract or rolling cycle ID (required for some categories)
       * @example null
       */
      target_id?: string | null;
      /**
       * Sub Id
       * Format: uuid
       * @description UUID of the sub on whose behalf the goddess is recording
       * @example 00000000-0000-0000-0000-000000000002
       */
      sub_id: string;
    };
    /** RefreshRequest */
    RefreshRequest: {
      /**
       * Refresh Token
       * @description Opaque refresh token previously issued by /auth/login or /auth/refresh
       * @example abc123
       */
      refresh_token: string;
    };
    /** RejectIn */
    RejectIn: {
      /**
       * Reason
       * @description Optional rejection reason shown to the sub
       * @example Wrong amount — expected £30.00
       */
      reason?: string | null;
    };
    /** ReorderRequest */
    ReorderRequest: {
      /**
       * Method Ids
       * @description Payment method IDs in the desired display order (index 0 = top)
       * @example [
       *       "00000000-0000-0000-0000-000000000001",
       *       "00000000-0000-0000-0000-000000000002"
       *     ]
       */
      method_ids: string[];
    };
    /** SignupRequest */
    SignupRequest: {
      /**
       * Email
       * @description Sub's email address
       * @example slave@example.com
       */
      email: string;
      /**
       * Password
       * @description Sub's password (min 8 characters)
       * @example s3cr3tP@ss
       */
      password: string;
      /**
       * Username
       * @description Unique username for the sub
       * @example slave42
       */
      username: string;
      /**
       * First Name
       * @description Sub's first name
       * @example John
       */
      first_name?: string | null;
      /**
       * Last Name
       * @description Sub's last name
       * @example Doe
       */
      last_name?: string | null;
    };
    /** TokenPair */
    TokenPair: {
      /**
       * Access Token
       * @description Short-lived JWT access token
       * @example eyJ...
       */
      access_token: string;
      /**
       * Refresh Token
       * @description Opaque refresh token (rotate on each use)
       * @example abc123
       */
      refresh_token: string;
      /**
       * Token Type
       * @description OAuth2 token type
       * @default bearer
       * @constant
       */
      token_type: "bearer";
      /**
       * Expires In
       * @description Access token lifetime in seconds
       * @example 900
       */
      expires_in: number;
    };
    /** UserOut */
    UserOut: {
      /**
       * Id
       * Format: uuid
       * @description User UUID
       * @example 00000000-0000-0000-0000-000000000001
       */
      id: string;
      /**
       * Email
       * Format: email
       * @description User email
       * @example sub@example.com
       */
      email: string;
      /**
       * @description User role
       * @example sub
       */
      role: components["schemas"]["UserRole"];
      /**
       * @description Account status
       * @example active
       */
      status: components["schemas"]["UserStatus"];
      /**
       * Display Name
       * @description User display name
       * @example Jane
       */
      display_name: string;
      /**
       * Avatar Url
       * @description Avatar URL
       * @example null
       */
      avatar_url?: string | null;
      /**
       * Theme Preference
       * @description UI theme preference
       * @example system
       */
      theme_preference: string;
      /**
       * Created At
       * Format: date-time
       * @description Account creation timestamp (UTC)
       */
      created_at: string;
    };
    /**
     * UserRole
     * @enum {string}
     */
    UserRole: "admin" | "goddess" | "sub";
    /**
     * UserStatus
     * @enum {string}
     */
    UserStatus: "pending_entry_tribute" | "active" | "blacklisted" | "deleted";
    /** ValidateIn */
    ValidateIn: {
      /**
       * @description Optional new category to assign before validating
       * @example null
       */
      recategorize_to?: components["schemas"]["PaymentCategory"] | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server is alive */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "ok"
           *     }
           */
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Unauthorized — missing or invalid credentials / token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — account inactive or role not permitted */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  refresh_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Unauthorized — missing or invalid credentials / token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logout_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  password_reset_request_auth_password_reset_request_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  password_reset_confirm_auth_password_reset_confirm_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetConfirm"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad request — invalid, used, or expired token */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_auth_me_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
      /** @description Unauthorized — missing or invalid credentials / token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_invitations_goddess_invitations__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvitationOut"][];
        };
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — caller is not a goddess or has no goddess profile */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_invitation_goddess_invitations__post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InvitationCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvitationOut"];
        };
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — caller is not a goddess or has no goddess profile */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_payment_methods_goddess_payment_methods__get: {
    parameters: {
      query?: {
        /** @description When true, return only enabled methods */
        enabled?: boolean;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentMethodOut"][];
        };
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — caller is not a goddess or has no goddess profile */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_payment_method_goddess_payment_methods__post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PaymentMethodCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentMethodOut"];
        };
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — caller is not a goddess or has no goddess profile */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_payment_method_goddess_payment_methods__method_id__delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        method_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — caller is not a goddess or has no goddess profile */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not found — payment method does not exist or belongs to another goddess */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_payment_method_goddess_payment_methods__method_id__patch: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        method_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PaymentMethodUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentMethodOut"];
        };
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — caller is not a goddess or has no goddess profile */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not found — payment method does not exist or belongs to another goddess */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  reorder_payment_methods_goddess_payment_methods_reorder_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentMethodOut"][];
        };
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — caller is not a goddess or has no goddess profile */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_invitation_invite__token__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicInvitationOut"];
        };
      };
      /** @description Not found — token does not exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Conflict — invitation has expired or has already been used */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  signup_via_invite_invite__token__signup_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Bad request — duplicate email or username */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not found — token does not exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Conflict — invitation expired, already used, or email/username taken */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_my_payments_sub_payments_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentOut"][];
        };
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — role or ownership mismatch */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  declare_payment_sub_payments_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeclarePaymentIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentOut"];
        };
      };
      /** @description Bad request — invalid category or business rule violation */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — role or ownership mismatch */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not found — declaration or resource does not exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  cancel_declaration_sub_payments__declaration_id__delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        declaration_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — role or ownership mismatch */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not found — declaration or resource does not exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Conflict — declaration is not in the expected status */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_declaration_sub_payments__declaration_id__patch: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        declaration_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditDeclarationIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentOut"];
        };
      };
      /** @description Bad request — invalid category or business rule violation */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — role or ownership mismatch */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not found — declaration or resource does not exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Conflict — declaration is not in the expected status */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_sub_payment_methods_sub_payment_methods_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentMethodOut"][];
        };
      };
      /** @description Bad request — invalid category or business rule violation */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — role or ownership mismatch */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_pending_payments_goddess_payments_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentOut"][];
        };
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — role or ownership mismatch */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  validate_declaration_goddess_payments__declaration_id__validate_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        declaration_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ValidateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentOut"];
        };
      };
      /** @description Bad request — invalid category or business rule violation */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — role or ownership mismatch */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not found — declaration or resource does not exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Conflict — declaration is not in the expected status */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  reject_declaration_goddess_payments__declaration_id__reject_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        declaration_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RejectIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentOut"];
        };
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — role or ownership mismatch */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not found — declaration or resource does not exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Conflict — declaration is not in the expected status */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  record_payment_goddess_payments_record_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecordPaymentIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentOut"];
        };
      };
      /** @description Bad request — invalid category or business rule violation */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — role or ownership mismatch */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not found — declaration or resource does not exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_goddess_subs_goddess_subs_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — role or ownership mismatch */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
