/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Returns `{"status": "ok"}` when the server process is running. Does not verify database connectivity — use this as a liveness probe only.
     */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Authenticate with email and password
     * @description Validates credentials and returns a JWT access token plus an opaque refresh token. The refresh token is stored hashed server-side and must be rotated on each use.
     */
    post: operations["login_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rotate refresh token and issue new access token
     * @description Consumes the provided refresh token (validates it is not revoked or expired), revokes it, and issues a new token pair. Rolling refresh — the old token becomes invalid.
     */
    post: operations["refresh_auth_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Revoke refresh token
     * @description Marks the supplied refresh token as revoked. Idempotent — calling with an already revoked or unknown token still returns 204.
     */
    post: operations["logout_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/password-reset/request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request a password reset email
     * @description Sends a password reset link to the supplied email if an account exists. Always returns 202 to prevent user enumeration.
     */
    post: operations["password_reset_request_auth_password_reset_request_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/password-reset/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Confirm password reset with token
     * @description Validates the reset token (checks expiry and not-used), sets the new password, and revokes all active refresh tokens for the user.
     */
    post: operations["password_reset_confirm_auth_password_reset_confirm_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Return the authenticated user's profile
     * @description Decodes the Bearer access token and returns the caller's profile.
     */
    get: operations["me_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/goddess/invitations/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all invitations created by the Goddess
     * @description Returns all invitations created by this Goddess, ordered newest first. Includes pending, expired, and used invitations.
     */
    get: operations["list_invitations_goddess_invitations__get"];
    put?: never;
    /**
     * Create an invitation link
     * @description Creates a new invitation token that a sub can use to sign up. Sets an entry tribute amount the sub must declare after signup. The invitation expires after `expires_in_days` days (default 7) and is single-use.
     */
    post: operations["create_invitation_goddess_invitations__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/invite/{token}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Fetch public invitation details
     * @description Returns the public information for a valid, unused, non-expired invitation. Used by the invitation landing page before the sub signs up.
     */
    get: operations["get_invitation_invite__token__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/invite/{token}/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sign up via invitation link
     * @description Creates a new sub account linked to the Goddess who owns the invitation. The sub is created with `status=pending_entry_tribute`. The invitation token is consumed atomically with user creation. Returns a token pair so the sub is immediately logged in.
     */
    post: operations["signup_via_invite_invite__token__signup_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InvitationCreate */
    InvitationCreate: {
      /**
       * Entry Tribute Amount
       * @description Entry tribute amount in GBP that the sub must declare on signup
       * @example 50.00
       */
      entry_tribute_amount: number | string;
      /**
       * Note
       * @description Optional private note visible to the sub on the invitation landing page
       * @example Welcome, slave.
       */
      note?: string | null;
      /**
       * Expires In Days
       * @description How many days from now until the invitation link expires
       * @default 7
       * @example 7
       */
      expires_in_days: number;
    };
    /** InvitationOut */
    InvitationOut: {
      /**
       * Id
       * Format: uuid
       * @description Invitation UUID
       * @example 00000000-0000-0000-0000-000000000001
       */
      id: string;
      /**
       * Token
       * @description URL-safe token embedded in the invite link
       * @example abc123xyz
       */
      token: string;
      /**
       * Url
       * @description Full invite URL to share with the sub
       * @example http://localhost:5173/invite/abc123xyz
       */
      url: string;
      /**
       * Entry Tribute Amount
       * @description Entry tribute amount in GBP
       * @example 50.00
       */
      entry_tribute_amount: string;
      /**
       * Note
       * @description Optional note
       * @example Welcome.
       */
      note?: string | null;
      /**
       * Expires At
       * Format: date-time
       * @description UTC expiry datetime of the invitation
       */
      expires_at: string;
      /**
       * Used At
       * @description UTC datetime when the invitation was consumed
       */
      used_at?: string | null;
      /**
       * Created At
       * Format: date-time
       * @description UTC datetime when the invitation was created
       */
      created_at: string;
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * @description User email address
       * @example sub@example.com
       */
      email: string;
      /**
       * Password
       * @description User password
       * @example s3cr3t!
       */
      password: string;
    };
    /** PasswordResetConfirm */
    PasswordResetConfirm: {
      /**
       * Token
       * @description Reset token from the email link
       * @example abc123
       */
      token: string;
      /**
       * New Password
       * @description New password to set (min 8 chars)
       * @example n3wP@ssw0rd
       */
      new_password: string;
    };
    /** PasswordResetRequest */
    PasswordResetRequest: {
      /**
       * Email
       * Format: email
       * @description Email address of the account to reset
       * @example sub@example.com
       */
      email: string;
    };
    /** PublicInvitationOut */
    PublicInvitationOut: {
      /**
       * Token
       * @description Invitation token
       * @example abc123xyz
       */
      token: string;
      /**
       * Goddess Display Name
       * @description Display name of the Goddess who created the invitation
       * @example Goddess Mean Mal
       */
      goddess_display_name: string;
      /**
       * Note
       * @description Optional note from the Goddess
       * @example Welcome.
       */
      note?: string | null;
      /**
       * Entry Tribute Amount
       * @description Amount the sub must tribute on signup (GBP)
       * @example 50.00
       */
      entry_tribute_amount: string;
      /**
       * Expires At
       * Format: date-time
       * @description UTC expiry datetime of the invitation
       */
      expires_at: string;
    };
    /** RefreshRequest */
    RefreshRequest: {
      /**
       * Refresh Token
       * @description Opaque refresh token previously issued by /auth/login or /auth/refresh
       * @example abc123
       */
      refresh_token: string;
    };
    /** SignupRequest */
    SignupRequest: {
      /**
       * Email
       * @description Sub's email address
       * @example slave@example.com
       */
      email: string;
      /**
       * Password
       * @description Sub's password (min 8 characters)
       * @example s3cr3tP@ss
       */
      password: string;
      /**
       * Username
       * @description Unique username for the sub
       * @example slave42
       */
      username: string;
      /**
       * First Name
       * @description Sub's first name
       * @example John
       */
      first_name?: string | null;
      /**
       * Last Name
       * @description Sub's last name
       * @example Doe
       */
      last_name?: string | null;
    };
    /** TokenPair */
    TokenPair: {
      /**
       * Access Token
       * @description Short-lived JWT access token
       * @example eyJ...
       */
      access_token: string;
      /**
       * Refresh Token
       * @description Opaque refresh token (rotate on each use)
       * @example abc123
       */
      refresh_token: string;
      /**
       * Token Type
       * @description OAuth2 token type
       * @default bearer
       * @constant
       */
      token_type: "bearer";
      /**
       * Expires In
       * @description Access token lifetime in seconds
       * @example 900
       */
      expires_in: number;
    };
    /** UserOut */
    UserOut: {
      /**
       * Id
       * Format: uuid
       * @description User UUID
       * @example 00000000-0000-0000-0000-000000000001
       */
      id: string;
      /**
       * Email
       * Format: email
       * @description User email
       * @example sub@example.com
       */
      email: string;
      /**
       * @description User role
       * @example sub
       */
      role: components["schemas"]["UserRole"];
      /**
       * @description Account status
       * @example active
       */
      status: components["schemas"]["UserStatus"];
      /**
       * Display Name
       * @description User display name
       * @example Jane
       */
      display_name: string;
      /**
       * Avatar Url
       * @description Avatar URL
       * @example null
       */
      avatar_url?: string | null;
      /**
       * Theme Preference
       * @description UI theme preference
       * @example system
       */
      theme_preference: string;
      /**
       * Created At
       * Format: date-time
       * @description Account creation timestamp (UTC)
       */
      created_at: string;
    };
    /**
     * UserRole
     * @enum {string}
     */
    UserRole: "admin" | "goddess" | "sub";
    /**
     * UserStatus
     * @enum {string}
     */
    UserStatus: "pending_entry_tribute" | "active" | "blacklisted" | "deleted";
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server is alive */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "ok"
           *     }
           */
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Unauthorized — missing or invalid credentials / token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — account inactive or role not permitted */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  refresh_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Unauthorized — missing or invalid credentials / token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logout_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  password_reset_request_auth_password_reset_request_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  password_reset_confirm_auth_password_reset_confirm_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetConfirm"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad request — invalid, used, or expired token */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_auth_me_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
      /** @description Unauthorized — missing or invalid credentials / token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_invitations_goddess_invitations__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvitationOut"][];
        };
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — caller is not a goddess or has no goddess profile */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_invitation_goddess_invitations__post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InvitationCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvitationOut"];
        };
      };
      /** @description Unauthorized — missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — caller is not a goddess or has no goddess profile */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_invitation_invite__token__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicInvitationOut"];
        };
      };
      /** @description Not found — token does not exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Conflict — invitation has expired or has already been used */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  signup_via_invite_invite__token__signup_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Bad request — duplicate email or username */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not found — token does not exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Conflict — invitation expired, already used, or email/username taken */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
