/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Returns `{"status": "ok"}` when the server process is running. Does not verify database connectivity — use this as a liveness probe only.
     */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Authenticate with email and password
     * @description Validates credentials and returns a JWT access token plus an opaque refresh token. The refresh token is stored hashed server-side and must be rotated on each use.
     */
    post: operations["login_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rotate refresh token and issue new access token
     * @description Consumes the provided refresh token (validates it is not revoked or expired), revokes it, and issues a new token pair. Rolling refresh — the old token becomes invalid.
     */
    post: operations["refresh_auth_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Revoke refresh token
     * @description Marks the supplied refresh token as revoked. Idempotent — calling with an already revoked or unknown token still returns 204.
     */
    post: operations["logout_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/password-reset/request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request a password reset email
     * @description Sends a password reset link to the supplied email if an account exists. Always returns 202 to prevent user enumeration.
     */
    post: operations["password_reset_request_auth_password_reset_request_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/password-reset/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Confirm password reset with token
     * @description Validates the reset token (checks expiry and not-used), sets the new password, and revokes all active refresh tokens for the user.
     */
    post: operations["password_reset_confirm_auth_password_reset_confirm_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Return the authenticated user's profile
     * @description Decodes the Bearer access token and returns the caller's profile.
     */
    get: operations["me_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * @description User email address
       * @example sub@example.com
       */
      email: string;
      /**
       * Password
       * @description User password
       * @example s3cr3t!
       */
      password: string;
    };
    /** PasswordResetConfirm */
    PasswordResetConfirm: {
      /**
       * Token
       * @description Reset token from the email link
       * @example abc123
       */
      token: string;
      /**
       * New Password
       * @description New password to set (min 8 chars)
       * @example n3wP@ssw0rd
       */
      new_password: string;
    };
    /** PasswordResetRequest */
    PasswordResetRequest: {
      /**
       * Email
       * Format: email
       * @description Email address of the account to reset
       * @example sub@example.com
       */
      email: string;
    };
    /** RefreshRequest */
    RefreshRequest: {
      /**
       * Refresh Token
       * @description Opaque refresh token previously issued by /auth/login or /auth/refresh
       * @example abc123
       */
      refresh_token: string;
    };
    /** TokenPair */
    TokenPair: {
      /**
       * Access Token
       * @description Short-lived JWT access token
       * @example eyJ...
       */
      access_token: string;
      /**
       * Refresh Token
       * @description Opaque refresh token (rotate on each use)
       * @example abc123
       */
      refresh_token: string;
      /**
       * Token Type
       * @description OAuth2 token type
       * @default bearer
       * @constant
       */
      token_type: "bearer";
      /**
       * Expires In
       * @description Access token lifetime in seconds
       * @example 900
       */
      expires_in: number;
    };
    /** UserOut */
    UserOut: {
      /**
       * Id
       * Format: uuid
       * @description User UUID
       * @example 00000000-0000-0000-0000-000000000001
       */
      id: string;
      /**
       * Email
       * Format: email
       * @description User email
       * @example sub@example.com
       */
      email: string;
      /**
       * @description User role
       * @example sub
       */
      role: components["schemas"]["UserRole"];
      /**
       * @description Account status
       * @example active
       */
      status: components["schemas"]["UserStatus"];
      /**
       * Display Name
       * @description User display name
       * @example Jane
       */
      display_name: string;
      /**
       * Avatar Url
       * @description Avatar URL
       * @example null
       */
      avatar_url?: string | null;
      /**
       * Theme Preference
       * @description UI theme preference
       * @example system
       */
      theme_preference: string;
      /**
       * Created At
       * Format: date-time
       * @description Account creation timestamp (UTC)
       */
      created_at: string;
    };
    /**
     * UserRole
     * @enum {string}
     */
    UserRole: "admin" | "goddess" | "sub";
    /**
     * UserStatus
     * @enum {string}
     */
    UserStatus: "pending_entry_tribute" | "active" | "blacklisted" | "deleted";
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server is alive */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "ok"
           *     }
           */
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Unauthorized — missing or invalid credentials / token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — account inactive or role not permitted */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  refresh_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Unauthorized — missing or invalid credentials / token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logout_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  password_reset_request_auth_password_reset_request_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  password_reset_confirm_auth_password_reset_confirm_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetConfirm"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad request — invalid, used, or expired token */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unprocessable entity — request body validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_auth_me_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
      /** @description Unauthorized — missing or invalid credentials / token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
