"""phase a1 b1 d1 e1 g1 h1 j1 foundation tables

Revision ID: 1de5e6292627
Revises: 5fab2f224eea
Create Date: 2026-04-16 19:42:35.723241

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1de5e6292627'
down_revision: str | None = '5fab2f224eea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goddess_kek',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goddess_id', sa.Uuid(), nullable=False),
    sa.Column('wrapped_dek', sa.LargeBinary(), nullable=False),
    sa.Column('root_kek_version', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goddess_id'], ['goddess.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goddess_kek_goddess_id'), 'goddess_kek', ['goddess_id'], unique=True)
    op.create_table('ritual',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sub_id', sa.Uuid(), nullable=False),
    sa.Column('goddess_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'custom', name='ritualfrequency'), nullable=False),
    sa.Column('custom_days_bitmask', sa.Integer(), nullable=True),
    sa.Column('deadline_time', sa.Time(), nullable=True),
    sa.Column('points_on_complete', sa.Integer(), nullable=False),
    sa.Column('points_on_miss', sa.Integer(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goddess_id'], ['goddess.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ritual_goddess_id'), 'ritual', ['goddess_id'], unique=False)
    op.create_index(op.f('ix_ritual_sub_id'), 'ritual', ['sub_id'], unique=False)
    op.create_table('sub_limit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sub_id', sa.Uuid(), nullable=False),
    sa.Column('goddess_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('hard', 'soft', name='limitkind'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='limitseverity'), nullable=False),
    sa.Column('acknowledged_by_goddess_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goddess_id'], ['goddess.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sub_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_limit_goddess_id'), 'sub_limit', ['goddess_id'], unique=False)
    op.create_index(op.f('ix_sub_limit_sub_id'), 'sub_limit', ['sub_id'], unique=False)
    op.create_table('sub_profile',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('real_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'non_binary', 'other', name='gender'), nullable=True),
    sa.Column('pronouns', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('joined_empire_at', sa.DateTime(), nullable=False),
    sa.Column('ownership_status', sa.Enum('free', 'owned', 'in_training', 'collared', 'blackmailed', 'released', name='ownershipstatus'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('sub_trigger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sub_id', sa.Uuid(), nullable=False),
    sa.Column('goddess_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_text', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='limitseverity'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goddess_id'], ['goddess.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sub_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_trigger_goddess_id'), 'sub_trigger', ['goddess_id'], unique=False)
    op.create_index(op.f('ix_sub_trigger_sub_id'), 'sub_trigger', ['sub_id'], unique=False)
    op.create_table('toy_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sub_id', sa.Uuid(), nullable=False),
    sa.Column('goddess_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('restraint', 'impact', 'vibrator', 'plug', 'cage', 'gag', 'clothing', 'collar', 'other', name='toycategory'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_r2_key', sa.Text(), nullable=True),
    sa.Column('proposed_by', sa.Enum('sub', 'goddess', name='toyproposedby'), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('lock_code_enc', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goddess_id'], ['goddess.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sub_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toy_item_goddess_id'), 'toy_item', ['goddess_id'], unique=False)
    op.create_index(op.f('ix_toy_item_sub_id'), 'toy_item', ['sub_id'], unique=False)
    op.create_table('payment_webhook_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('throne', 'paypal', 'revolut', 'cashapp', name='paymentwebhookprovider'), nullable=False),
    sa.Column('provider_event_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('result', sa.Enum('pending', 'matched', 'unmatched', 'duplicate', 'error', name='paymentwebhookresult'), nullable=False),
    sa.Column('matched_declaration_id', sa.Uuid(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('goddess_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['goddess_id'], ['goddess.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_declaration_id'], ['payment_declaration.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_webhook_event_provider_id')
    )
    op.create_index('ix_webhook_event_goddess_id', 'payment_webhook_event', ['goddess_id'], unique=False)
    op.create_index('ix_webhook_event_result', 'payment_webhook_event', ['result'], unique=False)
    op.create_table('ritual_occurrence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ritual_id', sa.Uuid(), nullable=False),
    sa.Column('sub_id', sa.Uuid(), nullable=False),
    sa.Column('goddess_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'missed', 'rejected', 'submitted', name='occurrencestatus'), nullable=False),
    sa.Column('evidence_photo_id', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goddess_id'], ['goddess.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ritual_id'], ['ritual.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ritual_id', 'date', name='uq_ritual_occurrence_ritual_date')
    )
    op.create_index(op.f('ix_ritual_occurrence_goddess_id'), 'ritual_occurrence', ['goddess_id'], unique=False)
    op.create_index(op.f('ix_ritual_occurrence_ritual_id'), 'ritual_occurrence', ['ritual_id'], unique=False)
    op.create_index(op.f('ix_ritual_occurrence_status'), 'ritual_occurrence', ['status'], unique=False)
    op.create_index(op.f('ix_ritual_occurrence_sub_id'), 'ritual_occurrence', ['sub_id'], unique=False)
    op.add_column('debt_contract', sa.Column('clauses_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('debt_contract', sa.Column('review_at', sa.DateTime(), nullable=True))
    op.add_column('debt_contract', sa.Column('renewal_policy', sa.Text(), server_default='none', nullable=False))

    # B1 backfill: every existing sub gets a default sub_profile row.
    op.execute(
        """
        INSERT INTO sub_profile (user_id, joined_empire_at, ownership_status)
        SELECT u.id, u.created_at, 'free'
        FROM "user" u
        WHERE u.role = 'sub'
          AND NOT EXISTS (SELECT 1 FROM sub_profile sp WHERE sp.user_id = u.id)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debt_contract', 'renewal_policy')
    op.drop_column('debt_contract', 'review_at')
    op.drop_column('debt_contract', 'clauses_json')
    op.drop_index(op.f('ix_ritual_occurrence_sub_id'), table_name='ritual_occurrence')
    op.drop_index(op.f('ix_ritual_occurrence_status'), table_name='ritual_occurrence')
    op.drop_index(op.f('ix_ritual_occurrence_ritual_id'), table_name='ritual_occurrence')
    op.drop_index(op.f('ix_ritual_occurrence_goddess_id'), table_name='ritual_occurrence')
    op.drop_table('ritual_occurrence')
    op.drop_index('ix_webhook_event_result', table_name='payment_webhook_event')
    op.drop_index('ix_webhook_event_goddess_id', table_name='payment_webhook_event')
    op.drop_table('payment_webhook_event')
    op.drop_index(op.f('ix_toy_item_sub_id'), table_name='toy_item')
    op.drop_index(op.f('ix_toy_item_goddess_id'), table_name='toy_item')
    op.drop_table('toy_item')
    op.drop_index(op.f('ix_sub_trigger_sub_id'), table_name='sub_trigger')
    op.drop_index(op.f('ix_sub_trigger_goddess_id'), table_name='sub_trigger')
    op.drop_table('sub_trigger')
    op.drop_table('sub_profile')
    op.drop_index(op.f('ix_sub_limit_sub_id'), table_name='sub_limit')
    op.drop_index(op.f('ix_sub_limit_goddess_id'), table_name='sub_limit')
    op.drop_table('sub_limit')
    op.drop_index(op.f('ix_ritual_sub_id'), table_name='ritual')
    op.drop_index(op.f('ix_ritual_goddess_id'), table_name='ritual')
    op.drop_table('ritual')
    op.drop_index(op.f('ix_goddess_kek_goddess_id'), table_name='goddess_kek')
    op.drop_table('goddess_kek')
    for enum_name in (
        'occurrencestatus',
        'paymentwebhookresult',
        'paymentwebhookprovider',
        'toyproposedby',
        'toycategory',
        'ownershipstatus',
        'gender',
        'limitseverity',
        'limitkind',
        'ritualfrequency',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
