"""invitations: table for entry-tribute invites

Revision ID: 2cb2c9d15b49
Revises: user_avatar_last_login
Create Date: 2026-04-13 22:39:19.226748

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2cb2c9d15b49"
down_revision: str | None = "user_avatar_last_login"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("goddess_id", sa.Uuid(), nullable=False),
        sa.Column("entry_tribute_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("used_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["goddess_id"],
            ["goddess.id"],
        ),
        sa.ForeignKeyConstraint(
            ["used_by_user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invitation_goddess_id"), "invitation", ["goddess_id"], unique=False)
    op.create_index(op.f("ix_invitation_token"), "invitation", ["token"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invitation_token"), table_name="invitation")
    op.drop_index(op.f("ix_invitation_goddess_id"), table_name="invitation")
    op.drop_table("invitation")
    # ### end Alembic commands ###
