"""debt contracts tables

Revision ID: 38f259f9ec7e
Revises: 5bd7b358ba49
Create Date: 2026-04-14 02:20:05.486834

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38f259f9ec7e"
down_revision: str | None = "5bd7b358ba49"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "debt_contract",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sub_id", sa.Uuid(), nullable=False),
        sa.Column("goddess_id", sa.Uuid(), nullable=False),
        sa.Column("sub_initiated", sa.Boolean(), nullable=False),
        sa.Column("principal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("interest_rate", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column(
            "interest_period", sa.Enum("monthly", "yearly", name="interestperiod"), nullable=False
        ),
        sa.Column("duration_periods", sa.Integer(), nullable=False),
        sa.Column(
            "payment_frequency",
            sa.Enum("weekly", "biweekly", "monthly", name="paymentfrequency"),
            nullable=False,
        ),
        sa.Column("minimum_payment", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "late_penalty_severity",
            sa.Enum("light", "medium", "severe", name="latepenaltyseverity"),
            nullable=False,
        ),
        sa.Column("late_penalty_percent", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("dom_can_add_surprise_penalty", sa.Boolean(), nullable=False),
        sa.Column(
            "mid_contract_addition_mode",
            sa.Enum(
                "disabled",
                "dom_controlled",
                "sub_approval_required",
                name="midcontractadditionmode",
            ),
            nullable=False,
        ),
        sa.Column("exit_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending_sub",
                "pending_dom",
                "pending_dom_counter",
                "pending_sub_signature",
                "active",
                "closed",
                "breached",
                "completed",
                "cancelled_by_dom",
                name="debtcontractstatus",
            ),
            nullable=False,
        ),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column("signed_pdf_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("signed_pdf_sha256", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("signed_at", sa.DateTime(), nullable=True),
        sa.Column("balance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["current_version_id"],
            ["debt_contract_version.id"],
            name="fk_debt_contract_current_version",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(["goddess_id"], ["goddess.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["sub_id"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_debt_contract_goddess_id"), "debt_contract", ["goddess_id"], unique=False
    )
    op.create_index(
        "ix_debt_contract_goddess_status", "debt_contract", ["goddess_id", "status"], unique=False
    )
    op.create_index(op.f("ix_debt_contract_sub_id"), "debt_contract", ["sub_id"], unique=False)
    op.create_index(
        "ix_debt_contract_sub_status", "debt_contract", ["sub_id", "status"], unique=False
    )
    op.create_table(
        "debt_contract_audit",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "proposed",
                "countered",
                "accepted_counter",
                "rejected_counter",
                "signed",
                "cancelled",
                "closed",
                "breached",
                "completed",
                name="debtcontracteventtype",
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "pending_sub",
                "pending_dom",
                "pending_dom_counter",
                "pending_sub_signature",
                "active",
                "closed",
                "breached",
                "completed",
                "cancelled_by_dom",
                name="debtcontractstatus",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "pending_sub",
                "pending_dom",
                "pending_dom_counter",
                "pending_sub_signature",
                "active",
                "closed",
                "breached",
                "completed",
                "cancelled_by_dom",
                name="debtcontractstatus",
            ),
            nullable=True,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["contract_id"], ["debt_contract.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_debt_contract_audit_contract_id"),
        "debt_contract_audit",
        ["contract_id"],
        unique=False,
    )
    op.create_table(
        "debt_contract_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("round_no", sa.Integer(), nullable=False),
        sa.Column("proposed_by", sa.Uuid(), nullable=False),
        sa.Column("proposed_at", sa.DateTime(), nullable=False),
        sa.Column("principal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("interest_rate", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column(
            "interest_period", sa.Enum("monthly", "yearly", name="interestperiod"), nullable=False
        ),
        sa.Column("duration_periods", sa.Integer(), nullable=False),
        sa.Column(
            "payment_frequency",
            sa.Enum("weekly", "biweekly", "monthly", name="paymentfrequency"),
            nullable=False,
        ),
        sa.Column("minimum_payment", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "late_penalty_severity",
            sa.Enum("light", "medium", "severe", name="latepenaltyseverity"),
            nullable=False,
        ),
        sa.Column("late_penalty_percent", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("dom_can_add_surprise_penalty", sa.Boolean(), nullable=False),
        sa.Column(
            "mid_contract_addition_mode",
            sa.Enum(
                "disabled",
                "dom_controlled",
                "sub_approval_required",
                name="midcontractadditionmode",
            ),
            nullable=False,
        ),
        sa.Column("exit_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["contract_id"], ["debt_contract.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["proposed_by"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contract_id", "round_no", name="uq_debt_contract_version_round"),
    )
    op.create_index(
        op.f("ix_debt_contract_version_contract_id"),
        "debt_contract_version",
        ["contract_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_debt_contract_version_contract_id"), table_name="debt_contract_version")
    op.drop_table("debt_contract_version")
    op.drop_index(op.f("ix_debt_contract_audit_contract_id"), table_name="debt_contract_audit")
    op.drop_table("debt_contract_audit")
    op.drop_index("ix_debt_contract_sub_status", table_name="debt_contract")
    op.drop_index(op.f("ix_debt_contract_sub_id"), table_name="debt_contract")
    op.drop_index("ix_debt_contract_goddess_status", table_name="debt_contract")
    op.drop_index(op.f("ix_debt_contract_goddess_id"), table_name="debt_contract")
    op.drop_table("debt_contract")
    # ### end Alembic commands ###
