"""d6_sub_medical_table

Revision ID: 5a94b6fde0ed
Revises: d833506ba52b
Create Date: 2026-04-16 20:56:57.980793

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a94b6fde0ed"
down_revision: str | None = "d833506ba52b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sub_medical",
        sa.Column("sub_id", sa.Uuid(), nullable=False),
        sa.Column("goddess_id", sa.Uuid(), nullable=False),
        sa.Column("dek_version", sa.Integer(), nullable=False),
        sa.Column("blood_type_enc", sa.LargeBinary(), nullable=True),
        sa.Column("allergies_enc", sa.LargeBinary(), nullable=True),
        sa.Column("medications_enc", sa.LargeBinary(), nullable=True),
        sa.Column("emergency_contact_enc", sa.LargeBinary(), nullable=True),
        sa.Column("medical_notes_enc", sa.LargeBinary(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["goddess_id"], ["goddess.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["sub_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sub_id"),
    )
    op.create_index(op.f("ix_sub_medical_goddess_id"), "sub_medical", ["goddess_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sub_medical_goddess_id"), table_name="sub_medical")
    op.drop_table("sub_medical")
    # ### end Alembic commands ###
