"""p1_1_signature_b64

Revision ID: 5fab2f224eea
Revises: 4f7724b0d433
Create Date: 2026-04-15 09:35:11.630267

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5fab2f224eea"
down_revision: str | None = "4f7724b0d433"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("debt_contract", sa.Column("signature_b64", sa.Text(), nullable=True))
    op.drop_column("debt_contract", "signed_pdf_url")
    op.drop_column("debt_contract", "signed_pdf_sha256")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "debt_contract",
        sa.Column("signed_pdf_sha256", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "debt_contract",
        sa.Column("signed_pdf_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("debt_contract", "signature_b64")
    # ### end Alembic commands ###
