"""payments: declarations and allocations with enums and indices

Revision ID: 9a073938a556
Revises: b968bd12a9df
Create Date: 2026-04-13 23:15:13.854810

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a073938a556"
down_revision: str | None = "b968bd12a9df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_declaration",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sub_id", sa.Uuid(), nullable=False),
        sa.Column("goddess_id", sa.Uuid(), nullable=False),
        sa.Column("method_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("external_timestamp", sa.DateTime(), nullable=True),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "entry",
                "rolling",
                "weekly_debt",
                "debt_payment",
                "buyout",
                "tribute",
                name="paymentcategory",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "validated", "rejected", "cancelled", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("declared_at", sa.DateTime(), nullable=False),
        sa.Column("validated_at", sa.DateTime(), nullable=True),
        sa.Column("validated_by", sa.Uuid(), nullable=True),
        sa.Column("rejection_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["goddess_id"], ["goddess.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["method_id"], ["payment_method.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["sub_id"], ["user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["validated_by"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_declaration_goddess_id"),
        "payment_declaration",
        ["goddess_id"],
        unique=False,
    )
    op.create_index(
        "ix_payment_declaration_goddess_status",
        "payment_declaration",
        ["goddess_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_declaration_method_id"), "payment_declaration", ["method_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_declaration_sub_id"), "payment_declaration", ["sub_id"], unique=False
    )
    op.create_index(
        "ix_payment_declaration_sub_status",
        "payment_declaration",
        ["sub_id", "status"],
        unique=False,
    )
    op.create_table(
        "payment_allocation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("declaration_id", sa.Uuid(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum(
                "entry",
                "rolling_cycle",
                "contract_debt",
                "contract_buyout",
                "tribute",
                name="allocationtargettype",
            ),
            nullable=False,
        ),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("allocated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["declaration_id"], ["payment_declaration.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("declaration_id", name="uq_payment_allocation_declaration"),
    )
    op.create_index(
        op.f("ix_payment_allocation_declaration_id"),
        "payment_allocation",
        ["declaration_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("password_reset_token_user_id_fkey"), "password_reset_token", type_="foreignkey"
    )
    op.create_foreign_key(None, "password_reset_token", "user", ["user_id"], ["id"])
    op.drop_constraint(op.f("refresh_token_user_id_fkey"), "refresh_token", type_="foreignkey")
    op.create_foreign_key(None, "refresh_token", "user", ["user_id"], ["id"])
    op.drop_constraint(op.f("user_goddess_id_fkey"), "user", type_="foreignkey")
    op.create_foreign_key(None, "user", "goddess", ["goddess_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_goddess_id_fkey"), "user", "goddess", ["goddess_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint(None, "refresh_token", type_="foreignkey")
    op.create_foreign_key(
        op.f("refresh_token_user_id_fkey"),
        "refresh_token",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "password_reset_token", type_="foreignkey")
    op.create_foreign_key(
        op.f("password_reset_token_user_id_fkey"),
        "password_reset_token",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_payment_allocation_declaration_id"), table_name="payment_allocation")
    op.drop_table("payment_allocation")
    op.drop_index("ix_payment_declaration_sub_status", table_name="payment_declaration")
    op.drop_index(op.f("ix_payment_declaration_sub_id"), table_name="payment_declaration")
    op.drop_index(op.f("ix_payment_declaration_method_id"), table_name="payment_declaration")
    op.drop_index("ix_payment_declaration_goddess_status", table_name="payment_declaration")
    op.drop_index(op.f("ix_payment_declaration_goddess_id"), table_name="payment_declaration")
    op.drop_table("payment_declaration")
    # ### end Alembic commands ###
