"""payment_methods: goddess payment method table

Revision ID: b968bd12a9df
Revises: 40ec9379ed96
Create Date: 2026-04-13 23:00:57.436144

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b968bd12a9df"
down_revision: str | None = "40ec9379ed96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_method",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("goddess_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("throne", "paypal", "bank", "other", name="paymentmethodtype"),
            nullable=False,
        ),
        sa.Column("handle_or_link", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["goddess_id"], ["goddess.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_method_goddess_id"), "payment_method", ["goddess_id"], unique=False
    )
    op.create_index(op.f("ix_payment_method_type"), "payment_method", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_method_type"), table_name="payment_method")
    op.drop_index(op.f("ix_payment_method_goddess_id"), table_name="payment_method")
    op.drop_table("payment_method")
    op.execute("DROP TYPE IF EXISTS paymentmethodtype")
    # ### end Alembic commands ###
